# Generated by Django 3.1.7 on 2021-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('businessName', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('jobName', models.CharField(max_length=255)),
                ('businessYear', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('businessType', models.CharField(max_length=255)),
                ('money', models.CharField(max_length=255)),
                ('pubTime', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Job',
                'ordering': ['jid'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('clazz', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('collage', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Student',
                'ordering': ['sid'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('clazz', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('collage', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Teacher',
                'ordering': ['tid'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=255)),
                ('upasswd', models.CharField(max_length=255)),
                ('utype', models.CharField(max_length=255)),
                ('fkno', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
                'ordering': ['uid'],
            },
        ),
    ]
