# Generated by Django 3.1.7 on 2021-03-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('collage', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Admin',
                'ordering': ['aid'],
            },
        ),
    ]
