# Generated by Django 3.1.7 on 2021-03-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
