# Generated by Django 3.1.7 on 2021-04-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_jobinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('pubTime', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('tid', models.IntegerField()),
            ],
            options={
                'db_table': 'Notice',
                'ordering': ['nid'],
            },
        ),
    ]
