# Generated by Django 3.1.7 on 2021-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNotice',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('nid', models.IntegerField()),
                ('sid', models.IntegerField()),
            ],
            options={
                'db_table': 'ReadNotice',
                'ordering': ['rid'],
            },
        ),
    ]
