# Generated by Django 3.1.7 on 2021-04-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_readnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward', models.TextField()),
                ('skill', models.TextField()),
                ('evaluate', models.TextField()),
                ('sid', models.IntegerField()),
            ],
            options={
                'db_table': 'Resume',
                'ordering': ['id'],
            },
        ),
    ]
