# Generated by Django 3.1.7 on 2021-04-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
