# Generated by Django 3.1.7 on 2021-04-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_business_businessandstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bid',
            field=models.IntegerField(null=True),
        ),
    ]
