# Generated by Django 3.1.7 on 2021-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0012_businessperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=255)),
                ('collegeAdmin', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'College',
                'ordering': ['id'],
            },
        ),
    ]
