# Generated by Django 3.1.7 on 2021-04-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0013_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
                ('subjectAdmin', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Subject',
                'ordering': ['id'],
            },
        ),
    ]
