# Generated by Django 3.1.7 on 2021-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0014_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessandstudent',
            name='jid',
            field=models.IntegerField(null=True),
        ),
    ]
